### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by tamis-laan** [stxxl/stxxl#11]
I am trying to compile the following code:

#include <iostream>
#include "stxxl/vector"
using namespace std;

int main(int argc, char** argv)
{
	stxxl::VECTOR_GENERATOR<int>::result my_vector;
	cout << "hello world" << endl;
}

Compiling using the following command:
g++ -I ./include/ -L ./lib/ -lstxxl main.cpp -o prog

which results in the following list of errors:

g++ -I ./include/ -L ./lib/ -lstxxl main.cpp -o prog
/tmp/ccWv9hqI.o: In function `stxxl::mutex::~mutex()':
main.cpp:(.text._ZN5stxxl5mutexD2Ev[_ZN5stxxl5mutexD5Ev]+0x43): undefined reference to `pthread_mutex_trylock'
/tmp/ccWv9hqI.o: In function `stxxl::check_library_version()':
main.cpp:(.text._ZN5stxxl21check_library_versionEv[_ZN5stxxl21check_library_versionEv]+0x5): undefined reference to `stxxl::version_major()'
main.cpp:(.text._ZN5stxxl21check_library_versionEv[_ZN5stxxl21check_library_versionEv]+0x1b): undefined reference to `stxxl::version_minor()'
main.cpp:(.text._ZN5stxxl21check_library_versionEv[_ZN5stxxl21check_library_versionEv]+0x31): undefined reference to `stxxl::version_patch()'
/tmp/ccWv9hqI.o: In function `stxxl::print_library_version_mismatch()':
main.cpp:(.text._ZN5stxxl30print_library_version_mismatchEv[_ZN5stxxl30print_library_version_mismatchEv]+0x33): undefined reference to `stxxl::get_library_version_string()'
main.cpp:(.text._ZN5stxxl30print_library_version_mismatchEv[_ZN5stxxl30print_library_version_mismatchEv]+0xbb): undefined reference to `stxxl::print_msg(char const*, std::string const&, unsigned int)'
/tmp/ccWv9hqI.o: In function `stxxl::config::config()':
main.cpp:(.text._ZN5stxxl6configC2Ev[_ZN5stxxl6configC5Ev]+0x9d): undefined reference to `stxxl::print_msg(char const*, std::string const&, unsigned int)'
/tmp/ccWv9hqI.o: In function `stxxl::config::check_initialized()':
main.cpp:(.text._ZN5stxxl6config17check_initializedEv[_ZN5stxxl6config17check_initializedEv]+0x23): undefined reference to `stxxl::config::initialize()'
/tmp/ccWv9hqI.o: In function `stxxl::disk_allocator::grow_file(long long)':
main.cpp:(.text._ZN5stxxl14disk_allocator9grow_fileEx[_ZN5stxxl14disk_allocator9grow_fileEx]+0x64): undefined reference to `stxxl::disk_allocator::add_free_region(long long, long long)'
/tmp/ccWv9hqI.o: In function `stxxl::random_number32::operator()() const':
main.cpp:(.text._ZNK5stxxl15random_number32clEv[_ZNK5stxxl15random_number32clEv]+0xa): undefined reference to `stxxl::ran32State'
main.cpp:(.text._ZNK5stxxl15random_number32clEv[_ZNK5stxxl15random_number32clEv]+0x1b): undefined reference to `stxxl::ran32State'
main.cpp:(.text._ZNK5stxxl15random_number32clEv[_ZNK5stxxl15random_number32clEv]+0x21): undefined reference to `stxxl::ran32State'
/tmp/ccWv9hqI.o: In function `stxxl::vector<int, 4u, stxxl::lru_pager<8u>, 2097152u, stxxl::RC, unsigned long long>::~vector()':
main.cpp:(.text._ZN5stxxl6vectorIiLj4ENS_9lru_pagerILj8EEELj2097152ENS_2RCEyED2Ev[_ZN5stxxl6vectorIiLj4ENS_9lru_pagerILj8EEELj2097152ENS_2RCEyED5Ev]+0x2c1): undefined reference to `stxxl::print_msg(char const*, std::string const&, unsigned int)'
main.cpp:(.text._ZN5stxxl6vectorIiLj4ENS_9lru_pagerILj8EEELj2097152ENS_2RCEyED2Ev[_ZN5stxxl6vectorIiLj4ENS_9lru_pagerILj8EEELj2097152ENS_2RCEyED5Ev]+0x35d): undefined reference to `stxxl::print_msg(char const*, std::string const&, unsigned int)'
main.cpp:(.text._ZN5stxxl6vectorIiLj4ENS_9lru_pagerILj8EEELj2097152ENS_2RCEyED2Ev[_ZN5stxxl6vectorIiLj4ENS_9lru_pagerILj8EEELj2097152ENS_2RCEyED5Ev]+0x41c): undefined reference to `stxxl::print_msg(char const*, std::string const&, unsigned int)'
/tmp/ccWv9hqI.o: In function `stxxl::singleton<stxxl::logger, true>::create_instance()':
main.cpp:(.text._ZN5stxxl9singletonINS_6loggerELb1EE15create_instanceEv[_ZN5stxxl9singletonINS_6loggerELb1EE15create_instanceEv]+0x8b): undefined reference to `stxxl::logger::logger()'
main.cpp:(.text._ZN5stxxl9singletonINS_6loggerELb1EE15create_instanceEv[_ZN5stxxl9singletonINS_6loggerELb1EE15create_instanceEv]+0x9c): undefined reference to `stxxl::register_exit_handler(void (*)())'
/tmp/ccWv9hqI.o: In function `stxxl::singleton<stxxl::config, true>::create_instance()':
main.cpp:(.text._ZN5stxxl9singletonINS_6configELb1EE15create_instanceEv[_ZN5stxxl9singletonINS_6configELb1EE15create_instanceEv]+0x9c): undefined reference to `stxxl::register_exit_handler(void (*)())'
/tmp/ccWv9hqI.o: In function `stxxl::singleton<stxxl::logger, true>::destroy_instance()':
main.cpp:(.text._ZN5stxxl9singletonINS_6loggerELb1EE16destroy_instanceEv[_ZN5stxxl9singletonINS_6loggerELb1EE16destroy_instanceEv]+0x2c): undefined reference to `stxxl::logger::~logger()'
/tmp/ccWv9hqI.o: In function `stxxl::singleton<stxxl::config, true>::destroy_instance()':
main.cpp:(.text._ZN5stxxl9singletonINS_6configELb1EE16destroy_instanceEv[_ZN5stxxl9singletonINS_6configELb1EE16destroy_instanceEv]+0x2c): undefined reference to `stxxl::config::~config()'
/tmp/ccWv9hqI.o: In function `stxxl::singleton<stxxl::block_manager, true>::create_instance()':
main.cpp:(.text._ZN5stxxl9singletonINS_13block_managerELb1EE15create_instanceEv[_ZN5stxxl9singletonINS_13block_managerELb1EE15create_instanceEv]+0x8b): undefined reference to `stxxl::block_manager::block_manager()'
main.cpp:(.text._ZN5stxxl9singletonINS_13block_managerELb1EE15create_instanceEv[_ZN5stxxl9singletonINS_13block_managerELb1EE15create_instanceEv]+0x9c): undefined reference to `stxxl::register_exit_handler(void (*)())'
/tmp/ccWv9hqI.o: In function `stxxl::singleton<stxxl::block_manager, true>::destroy_instance()':
main.cpp:(.text._ZN5stxxl9singletonINS_13block_managerELb1EE16destroy_instanceEv[_ZN5stxxl9singletonINS_13block_managerELb1EE16destroy_instanceEv]+0x2c): undefined reference to `stxxl::block_manager::~block_manager()'
/tmp/ccWv9hqI.o: In function `stxxl::simple_vector<stxxl::BID<2097152u> >::resize(unsigned long)':
main.cpp:(.text._ZN5stxxl13simple_vectorINS_3BIDILj2097152EEEE6resizeEm[_ZN5stxxl13simple_vectorINS_3BIDILj2097152EEEE6resizeEm]+0x88): undefined reference to `stxxl::print_msg(char const*, std::string const&, unsigned int)'
/tmp/ccWv9hqI.o: In function `void stxxl::disk_allocator::delete_block<2097152u>(stxxl::BID<2097152u> const&)':
main.cpp:(.text._ZN5stxxl14disk_allocator12delete_blockILj2097152EEEvRKNS_3BIDIXT_EEE[_ZN5stxxl14disk_allocator12delete_blockILj2097152EEEvRKNS_3BIDIXT_EEE]+0x55): undefined reference to `stxxl::disk_allocator::add_free_region(long long, long long)'
/tmp/ccWv9hqI.o: In function `void* stxxl::aligned_alloc<4096ul>(unsigned long, unsigned long)':
main.cpp:(.text._ZN5stxxl13aligned_allocILm4096EEEPvmm[_ZN5stxxl13aligned_allocILm4096EEEPvmm]+0x1e0): undefined reference to `stxxl::print_msg(char const*, std::string const&, unsigned int)'
/tmp/ccWv9hqI.o: In function `void stxxl::disk_allocator::new_blocks<2097152u>(stxxl::BID<2097152u>*, stxxl::BID<2097152u>*)':
main.cpp:(.text._ZN5stxxl14disk_allocator10new_blocksILj2097152EEEvPNS_3BIDIXT_EEES4_[_ZN5stxxl14disk_allocator10new_blocksILj2097152EEEvPNS_3BIDIXT_EEES4_]+0x155): undefined reference to `stxxl::print_msg(char const*, std::string const&, unsigned int)'
main.cpp:(.text._ZN5stxxl14disk_allocator10new_blocksILj2097152EEEvPNS_3BIDIXT_EEES4_[_ZN5stxxl14disk_allocator10new_blocksILj2097152EEEvPNS_3BIDIXT_EEES4_]+0x31d): undefined reference to `stxxl::print_msg(char const*, std::string const&, unsigned int)'
main.cpp:(.text._ZN5stxxl14disk_allocator10new_blocksILj2097152EEEvPNS_3BIDIXT_EEES4_[_ZN5stxxl14disk_allocator10new_blocksILj2097152EEEvPNS_3BIDIXT_EEES4_]+0x34a): undefined reference to `stxxl::disk_allocator::dump() const'
main.cpp:(.text._ZN5stxxl14disk_allocator10new_blocksILj2097152EEEvPNS_3BIDIXT_EEES4_[_ZN5stxxl14disk_allocator10new_blocksILj2097152EEEvPNS_3BIDIXT_EEES4_]+0x3e6): undefined reference to `stxxl::print_msg(char const*, std::string const&, unsigned int)'
collect2: error: ld returned 1 exit status

Note: I compiled the dynamic library from source

**Comment by bingmann** [comment]
You probably found out by now that the compile line is wrong. Libraries belong at the end.
