### ISSUE TITLE
is old bugzilla at stxxl.ae.cs.uni-frankfurt.de/bugs/ dead?

### ISSUE THREAD

**Issue by datjko** [stxxl/stxxl#12]
It seems the old bugzilla (stxxl.ae.cs.uni-frankfurt.de/bugs/) mentioned as a place where to report bugs on http://stxxl.sourceforge.net/tags/1.3.1/ is dead and even does not exists as a copy in archive.org. It's pity as I wanted to reference a couple of bugs there, including one I reported myself. Is it dead forever and if yes is it still available somewhere in a read-only form?

**Comment by bingmann** [comment]
Yes, I believe the bugzilla is permanently dead, I also dont have the data to resurrect it in read-only form. Keeping a php framework like bugzilla up to date is no fun.
I moved all open issues into the TODO file somewhen before 1.4.0.
