### ISSUE TITLE
stxxl 1.3.1: crash after unsuccessful resize of stxxl::vector

### ISSUE THREAD

**Issue by datjko** [stxxl/stxxl#13]
If stxxl::vector::resize(n) throws an exception due to insufficient disk space the vector object will crash in it's destructor. Looking at the crash in a debugger I see the stack like this:
block_manager::delete_blocks(begin, end)
    -> block_manager::delete_block(bid)
        -> bid.is_managed() // here
and the reason for the crash is that bid.storage is null.
The problem is gone after I changed
https://github.com/stxxl/stxxl/blob/1.3.1/include/stxxl/bits/mng/mng.h#L208 line 208
from if (!bid.is_managed())
to if (!bid.valid() || !bid.is_managed())
Would be great to know if this problem is fixed in 1.4.x?

**Comment by bingmann** [comment]
I remember one commit, 0241c7b7e52b314d3f4a5a456fe30e480a24237a, which does something with resize() but that's not about lack of disk space.
Can you write a simple test case?

**Comment by datjko** [comment]
I believe something like following should reproduce it:

0. I had it on Windows 7, MSVC 2010, x64 if it matters
1. in stxxl.config set one and only stxxl disk to a file on a flash drive and make sure the flash card has only few Mb of free space.
2. run something like the following:
//--------------- test.cpp
#include <stxxl.h>
typedef stxxl::VECTOR_GENERATOR<int, 4, 4>::result vector_type;
int main(int argc, char * argv[]) {
    vector_type* vector = new vector_type(); // I remember the problem I had was with stxxl vector not bounded to a file directly. I don't know if it matters.
    try {
        while(true)
            vector->push_back(0);
    }
    catch(...) {
        delete vector; // here it will crash in block_manager::delete_block(bid)
    }
    return 0;
}

**Comment by bingmann** [comment]
I think I fixed the problem with 465c8d963fdf58155bb9eb9f129f5ad6cb0d7843

**Comment by datjko** [comment]
Hello Timo,

I did not yet try to verify the problem is gone in the main branch but from
looking into your changes I believe it's fixed now. I'll let you know about
any problems when I switch to new version of stxxl or evaluate the version
from the main branch.

Thank you,
David
