### ISSUE TITLE
Just to notify a little mistake in the tutorial_map.dox 

### ISSUE THREAD

**Issue by pierre33** [stxxl/stxxl#16]
In line 52:
"If CompareGreater()(a,b) is true, then a is smaller than b".
I think you mean the opposite right ?
Also in line 54:
"Naturally, we can define a comparator class which returns true if b is smaller than a as follow."
Anyway, I am currently studying STXXL to use it for a classification algorithm dealing with huge amount of data. This library is really great and do the job when data can not fit into the main memory.
I wish you a good continuation and if you are interested you can look at my github website:
http://pierre33.github.io/

Regards,
Lassalle Pierre

**Comment by bingmann** [comment]
Thanks.
