### ISSUE TITLE
Deprecated hash_map header

### ISSUE THREAD

**Issue by alex85k** [stxxl/stxxl#17]
Newer Visual Studio 2015 RC stopped compilig deprecated hash_map header
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\hash_map(17): error C2338: <hash_map> is deprecated and will be REMOVED. Please use <unordered_map>. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that you have received this warning. [D:\winbuilds\stxxl\build\tools\stxxl_tool.vcxproj]
```

I guess that <unordered_map> should be activated in https://github.com/stxxl/stxxl/blob/master/include/stxxl/bits/compat/hash_map.h#L24 for _MSC_VER >= 1900 . Not sure about the best solution, so there is no PR.

**Comment by alex85k** [comment]
The workaround: https://github.com/alex85k/stxxl/commit/898fa3760c0a836188229974da63641460184a90

**Comment by bingmann** [comment]
Yes, I think you should make a merge request.

**Comment by alex85k** [comment]
See work in progress in https://github.com/thk1/stxxl , no need in separate merge request,,,
