### ISSUE TITLE
spin_lock misses the default constructor on newer MSVC

### ISSUE THREAD

**Issue by alex85k** [stxxl/stxxl#18]
When compiling under new Visual Studio 2015 RC I am getting the error about missing default constructor in ``spin_lock`` class. It is really turned off for MSC_VER 1800 and 1900 . Should it be returned in #else block?

https://github.com/stxxl/stxxl/blob/master/include/stxxl/bits/common/mutex.h#L167

**Comment by alex85k** [comment]
I have made this: https://github.com/alex85k/stxxl/commit/691c3e22f76a9a85b393407f628f61472b9868fe

**Comment by bingmann** [comment]
Yes, I think you should make a merge request. I dont know about visual studios details either.

**Comment by orens** [comment]
If I understand correctly, this is the correct solution (since an empty constructor is what needed when aggregate initialization is available)
@alex85k / @bingmann , can any of you PR? Want me to create it?
