### ISSUE TITLE
stxxl does not compile with VS2013

### ISSUE THREAD

**Issue by programmer-art** [stxxl/stxxl#21]
Checked out, processed with CMake in order to get Vs2013 Solution and build.

Error is:

**D:\repositories_ext\stxxl\include\stxxl/bits/common/mutex.h(187): error C2797: 'stxxl::spin_lock::lck': list initialization inside member initializer list or non-static data member initializer is not implemented**

If I change STXXL_MSVC from 1800 to 1700 under VS 2013(1800), compilation succeeds. With this change, I get rid of the initialization in the class definition of spin_lock.

Do I do anything wrong here?

Thanks.

**Comment by bingmann** [comment]
Maybe @MarcusFree can clarity this, I dont natively work on Windows.

**Comment by manpen** [comment]
The new release will require VS17+.
