### ISSUE TITLE
CentOS 7 compile stxxl

### ISSUE THREAD

**Issue by cheburan** [stxxl/stxxl#22]
Trying to compile stxxl for OSRM on CentOS7 according to Building-OSRM guid

On the step of 
"cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/opt/osrm_infrastructure/stxx -DBUILD_STATIC_LIBS=ON .."

reciving an error message (screenshot atached below)

![image](https://cloud.githubusercontent.com/assets/11454021/9567691/1cb73fe2-4f3d-11e5-8d70-34bad9b080b2.png)

Sorry if the question a little bit naive, I can't find any information about this issue.

**Comment by bingmann** [comment]
I would suggest you google how to install thread libraries first, before flagging this as an issue of the library.
