### ISSUE TITLE
map.count() is not const

### ISSUE THREAD

**Issue by csaftoiu** [stxxl/stxxl#23]
See [line 277 in stxxl/bits/containers/map.h](https://github.com/stxxl/stxxl/blob/master/include/stxxl/bits/containers/map.h#L277):

    size_type count(const key_type& k)
    {
        return impl.count(k);
    }

This should be a `const` function, non?

**Comment by bingmann** [comment]
I fear that `count()` may change the internal state of the btree, since it may have to load pages from disk. Hence, the function is not const.

**Comment by csaftoiu** [comment]
Ah yes, I see your point. I suggest it should still be const anyway - in this case const would mean not "physical" constness (nothing modified) but ["logical" constness](http://stackoverflow.com/questions/3830367/difference-between-logical-and-physical-const-ness). From one of the answers on that question, emphasis mine:

> A `mutable` class member can be modified even if the class object itself (or the reference or pointer used to access it) is `const`. Examples of good uses of this are a mutex that must be locked during a read operation, and a cache to store the result of an expensive read operation. In both cases, **the operation itself should be a `const` function (since it doesn't affect the visible state of the object)**, but it needs to modify the mutex or the cache, so these need to be `mutable`. It can also be abused to make the object visibly change when logically it shouldn't, so use it with care; only declare members `mutable` if they don't form part of the externally visible state.

Anyways, just a suggestion - thanks for the great library.
