### ISSUE TITLE
[BUG] Bug in unordered_map/hash_map empty() method, returns "not-empty()".

### ISSUE THREAD

**Issue by adishavit** [stxxl/stxxl#38]
[`hash_map.h` line 298](https://github.com/stxxl/stxxl/blob/1babe452214b4613a2a488d80073f4185c05a0b3/include/stxxl/bits/containers/hash_map/hash_map.h#L298) 
```
    //! Check if container is empty.
    bool empty() const
    {
        return size() != 0; // should be size() == 0
    }
```

**Comment by bingmann** [comment]
This should be a pull request not an issue.
