### ISSUE TITLE
C++11 compliancy

### ISSUE THREAD

**Issue by duckie** [stxxl/stxxl#4]
What about it ?

**Comment by bingmann** [comment]
If someone wants a fun project, they could add all the emplace_back, and further constructors to the containers.

**Comment by DennisOSRM** [comment]
Are you thinking of switching to C++11 for good or to #ifdef the code providing these method implementations only when compiling in C++11 mode?

**Comment by bingmann** [comment]
I think it's easiest to #ifdef those parts with __cplusplus >= ...

**Comment by manpen** [comment]
This (and more) will be part of our next release
