### ISSUE TITLE
Resize a stxxl::vector may fail to expand the vector with initialization

### ISSUE THREAD

**Issue by shiyuan** [stxxl/stxxl#45]
Hello,
I'm trying to use `stxxl::vector` to pack my class object, after resizing it, most of the elements are not well value-initialized by the user-declared constructor.

Here is a toy code to show the `resize()` will not expand the content  with initialization after a loop-value(according to the size of the vector's element, e.g.uint64_t may get a loop of 8388608).

```
#include <stxxl/vector>
#include <iostream>
#include <vector>
int main()
{
    stxxl::vector<std::uint64_t> vec;
    //std::vector<std::uint64_t> vec;
    std::uint64_t limit = 8388619;
    vec.resize(limit);
    for (std::uint64_t i = 0; i < limit; ++i)
    {
        if (vec[i] != 0)
        {
            std::cout << i << ":" << vec[i] << std::endl;
        }
        vec[i] = i * i;
    }
    return 0;
}
```
then print
```
8388609:1
8388610:4
8388611:9
8388612:16
8388613:25
8388614:36
8388615:49
8388616:64
8388617:81
8388618:100
```

Hope this helps.  ^_^

**Comment by manpen** [comment]
Dear shiyuan,

thank you for your report. What you see is, that elements of pages in internal memory are default constructed, while page currently not in IM are not. This is in fact intended behaviour and agrees with the documentation "vector::resize [..] Warning; this will not call the constructor of objects in external memory!".
This is an optimisation to avoid expensive I/Os. If you want to initialize the values, please use a bufwriter (or similiar) to explicitly set the values.

``
stxxl::vector<std::uint64_t>::bufwriter_type writer(vec);
for(uint64_t i; i<limit; ++i)
  writer << 0;
writer.finish();
``

This however is often not necessary and can be typically avoided by tweaking the algorithm. Also, dynamic growth of an EM vector typically incurs less penalties than growing an IM vector.

**Comment by shiyuan** [comment]
I see, thanks for the great library.
