### ISSUE TITLE
How I make a config for stxxl?

### ISSUE THREAD

**Issue by cyb3727** [stxxl/stxxl#63]
When I run a stxxl application, It shows that:
[STXXL-ERRMSG] Warning: no config file found

How should I make a configuration?

**Comment by manpen** [comment]
Please refer to the documentation http://stxxl.org/tags/1.4.1/install_config.html .
Also, you may want to have look at http://panthema.net/2014/0622-Talk-STXXL-1.4.0-and-Beyond/
