### ISSUE TITLE
Requirements of algos and containers on KeyExtractor/Comparators

### ISSUE THREAD

**Issue by manpen** [stxxl/stxxl#75]
KeyExtracts may or may not have to provide min/max values.
Name Template Params: KeyExtract, KeyExtractWithMin, KeyExtractWithMax, KeyExtractWithMinMax

Comparators may/may partially or may not have to provide sentinels.
Name Template Params: Compare, CompareWithMin, CompareWithMax, CompareWithMinMax

**Comment by AbcAeffchen** [comment]
Closed in bingmann/stxxl@c96214428af4922bca55b6103ca2bed44b6234c5.
