### ISSUE TITLE
Fix documentation to include foxxll/tlx and reference the correct types

### ISSUE THREAD

**Issue by michitux** [stxxl/stxxl#79]
The stxxl documentation currently includes design documentation for the block layer that references a lot of types that are now in foxxl. Also stuff from tlx is referenced/included like the example of the command line parser. The foxxl and tlx documentation should be included in stxxl and the references fixed.

**Comment by bingmann** [comment]
Done somwhat with c380a8c8c2480477b10d67b0d8eb5421b60148dc
