### ISSUE TITLE
Does stxxl's containers support embed "std::vector" into user-defined type? 

### ISSUE THREAD

**Issue by NanXiao** [stxxl/stxxl#89]
Hi all,

Greetings from me!

I write a simple program using `stxxl's vector`:  

```
#include <stxxl/vector>
#include <vector>
#include <iostream>

class Foo
{
public:
    std::vector<double> vec;
    Foo()
    {
    }
};

int main()
{
    typedef stxxl::VECTOR_GENERATOR<Foo>::result vector;
    vector my_vector;
    std::cout.precision(10);

    for (int i = 0; i < 1024 * 1024 * 1024; i++)
    {
        my_vector.push_back(Foo());
        my_vector[i].vec.push_back(i);
    }


    std::cout << my_vector[99].vec[0] << std::endl;

    return 0;
}
```

You can see the user-defined type `Foo` contains a `std::vector`. I expect the running result is `99`, but in fact the output is `1073737827` . I guess the `stxxl's vector` did "resize" operation, but not sure.  

So does `stxxl`'s containers support embed `std::vector` into user-defined type? Thanks very much in advance!

Best Regards
Nan Xiao

**Comment by manpen** [comment]
Dear Nan Xiao,

STXXL cannot deal with memory indirections (which for instance rules out the usage of std::vector). See eg,

> STXXL containers differ from STL containers in treating allocation and distinguishing between uninitialized and initialized memory. STXXL containers assume that the data types they store are plain old data types (POD). The constructors and destructors of the contained data types are not called when a container changes its size. The support of constructors and destructors would imply a significant I/O cost penalty, e.g. on the deallocation of a non-empty container, one has to load all contained objects and call their destructors. This restriction sounds more severe than it is, since external memory data structures cannot cope with custom dynamic memory management anyway, which is the common use of custom constructors/destructors. However, we plan to implement special versions of STXXL containers which will support not only PODs, and handle construction/destruction appropriately.

https://stxxl.org/tags/1.4.1/design_stl_containers.html

If you need to support data of variable length then the default approach is to manually split larger object, by e.g. using std::tuple<index, chunk_id, payload> which you later reconstruct. There are in fact future plans to support serialization/deserialization at least for some containers; however, no work into this direction has been done yet. Feel free to contribute :)

**Comment by NanXiao** [comment]
@manpen 

Thanks  very much for your reply!

The initial idea of using `std::vector` originates from a 3rd-party library which I use doesn't provide default constructor for type `Foo` (plz refer #88). So I come out the idea of encapsulating a wrapper class:  

```
class WrapperFoo
{
public:
    std::vector<Foo> vec;
    WrapperFoo()
    {
    }
}
```

From your explanation, it seem `stxxl` can't support this scenario. Is my understanding correct? Thanks very much in advance!

Best Regards
Nan Xiao

**Comment by manpen** [comment]
Yes, that's unfortunately the case

**Comment by NanXiao** [comment]
@manpen 

Sorry for interrupting you again, please forgive my verbose talk. I just want to make sure the default constructor issue:  

The summary is if the user-defined type doesn't have default constructor, `stxxl` is not appropriate for it. There is no good work-around method for this type. 

Is my understanding correct? Thanks very much in advance!

Best Regards
Nan Xiao
