### ISSUE TITLE
can the container be loaded back from file created by stxxl

### ISSUE THREAD

**Issue by cahuja1992** [stxxl/stxxl#97]
Write the index
    stxxl::config * cfg = stxxl::config::get_instance();
    stxxl::disk_config disk1("disk=/tmp/lsh.index, 10 GiB, syscall unlink");
    disk1.direct = stxxl::disk_config::DIRECT_ON; // force O_DIRECT
    disk1.delete_on_exit = false;
    cfg->add_disk(disk1);

What could be the possible way to read the file "/tmp/lsh.index" ?

**Comment by bingmann** [comment]
Generally no, because STXXL stores data structures as blocks in the file, but the metadata is kept in the program's RAM.

**Comment by cahuja1992** [comment]
> s in the file, but the metadata is kept in the program's RAM.

Oh okay thanks
